from dash import html


content = html.Div(
    [
        html.H4("Summary"),
        html.P(
            """
The purpose of this tool is to interact with outputs generated by the Incytr pathway discovery tool (citation).

There are two main visualizations -- a directed graph and a river plot -- which can be filtered on a number of criteria. 

Directed Graph
The directed graph is a high-level view of the number of pathways occurring between celltypes, and

River Plot
The river plot displays the molecular components (ligand, receptor, effector, and target gene) of the detected pathways. If >= 75 targets pass the current filters, they will be hidden. However, the targets will still be listed in the downloaded dataset.

Downloading Data

Click "Download CSV" to download data passing the current filters.

A zip archive with 3 files will be produced:

-- CSV of pathways passing current filters for condition A
-- CSV of pathways passing current filters for condition B
-- YAML file with the parameters/filters that produced the above files


Troubleshooting




"""
        ),
    ]
)
