name: Test on Windows

on:
  push:
    branches: [windows-support]
  pull_request:
    branches: [windows-support]

jobs:
  build:
    runs-on: windows-latest # Use the latest Windows version

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install . && pip install pytest
      - name: Run tests
        run: pytest -k test_serve_app test.py
